### ISSUE TITLE
Why don't ElectionIdentifier and ElectionSource foreign key fields have the same name?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/python-opencivicdata#3]
As seen [here](https://github.com/california-civic-data-coalition/python-opencivicdata/blob/master/opencivicdata/elections/models/election.py#L64-L93), the Election foreign key field on ElectionIdentifier is named "election" while the one on ElectionSource is called "event." Is there a reason?

```python

@python_2_unicode_compatible
class ElectionIdentifier(IdentifierBase):
    """
    Upstream identifiers of the election, if any exist.
    For example, identfiers assigned by a Secretary of State, county or city
    elections office.
    """
    election = models.ForeignKey(
        Election,
        related_name='identifiers',
        help_text="Reference to the Election identified by the identifier.",
    )

    class Meta:
        db_table = 'opencivicdata_electionidentifier'

    def __str__(self):
        tmpl = '%s identifies %s'
        return tmpl % (self.identifier, self.election)


class ElectionSource(LinkBase):
    """
    Source used in assembling the Election.
    """
    event = models.ForeignKey(Election, related_name='sources')

    class Meta:
        db_table = 'opencivicdata_electionsource'
```

**Comment by gordonje** [comment]
Just an oversight. Elections previous subclassed events, but now this relationship is more conceptual.

**Comment by palewire** [comment]
So the ElectionSource should change its field's name to "election?"

**Comment by gordonje** [comment]
Yes. That's that should be the name for the field everywhere else (e.g., on the contest models).

**Comment by palewire** [comment]
Alrighty. I've shipped a pull request to the maintainers. https://github.com/opencivicdata/python-opencivicdata/pull/103
